Correction des erreurs, ajout et suppression des utilisateurs
Tgarfr/P2-DA-Android pull request #1
Opened 2022-08-22 11:26 UTC by Tgarfr

Correction des erreurs : 
- generateRandomUserWithSuccess
- getUsersWithSuccess
- deleteUserWithSuccess

Fonctionnalité ajoutés
- Suppression des utilisateurs
- Ajout d'un utilisateur aléatoire

2022-08-22 18:09 UTC, FGuyet requested changes

2022-08-22 18:09 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/magicgithub/repository/UserRepository.java
> +    private final FakeApiService apiService; // TODO: A utiliser
Il vaut mieux garder l'apiService en tant qu'ApiService, ce qui oblige à utiliser l'objet avec les méthodes de l'interface, et plus tard passer plus facilement de FakeApiService à un Service qui retourne de la vraie donnée, tout en limitant le nombre de choses à modifier.  

```suggestion
    private final ApiService apiService;
```

Une instance de FakeApiService est passée au constructeur de UserRepository, rien à modifier ici : https://github.com/OpenClassrooms-Student-Center/P2-DA-Android/blob/21fabcc1b9b112925344f8771dae44b5c0ba53ef/app/src/main/java/com/openclassrooms/magicgithub/di/Injection.java#L9

2022-08-22 18:09 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/magicgithub/repository/UserRepository.java
> +    public UserRepository(FakeApiService apiService) {
```suggestion
    public UserRepository(ApiService apiService) {
```

2022-08-22 18:14 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/magicgithub/api/FakeApiService.java
>          // TODO: A modifier
Tu peux les retrouver facilement avec l'outil `View > Tool Windows > TODO`

2022-08-24 05:04 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/magicgithub/api/FakeApiService.java
>          // TODO: A modifier
Ok merci

2022-08-24 05:36 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/magicgithub/repository/UserRepository.java
> +    private final FakeApiService apiService; // TODO: A utiliser
Au début je pensait que cette ligne crée une instance de l'interface ApiService, ce qui n'est pas possible pour une interface.
Mais du coup cette commande crée un objet dont le type est défini par ce qui est injecté dedans par apiService du constructeur de la classe UserRepository, et ce type est forcément une classe dérivé de ApiService.

2022-08-24 07:06 UTC, FGuyet approved these changes

2022-08-29 11:59 UTC, merged